import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import ThemeProvider from '@/components/ThemeProvider';

import './globals.css';

import NextAuthProvider from '@/components/NextAuthProvider';
import ThemeToggleBtn from '@/components/ThemeProvider/ThemeToggleBtn';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <main className="flex h-screen flex-col items-center justify-center">{children}</main>
            <ThemeToggleBtn />
          </ThemeProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
